FederalBank/FederalBank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('', include('bank.urls')),
    path('admin/', admin.site.urls),
]

FederalBank/bank/urls.py
from django.urls import path, include
from .import views



urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_usr, name='login'),
    path("logout", views.logout_usr, name='logout'),
    path('register', views.register, name="register"),
    path("account_created", views.acc_created, name='acc_created'),
    path("profile", views.profile, name='profile'),
    path("profile/edit", views.edit_profile, name='edit_profile'),
    path("change-password", views.change_password, name='change_password'),
    path("change-password-done", views.password_changed, name='password_changed'),
    path("reset-password/<int:user_id>", views.reset_password, name='reset_password'),
    path("administrator-menu", views.administrator_menu, name='administrator_menu'),
    path("suport-client-menu", views.suport_client_menu, name='suport_client_menu'),
    path("client-menu", views.client_menu, name='client_menu'),
    path("transaction-menu", views.transaction_menu, name='transaction_menu'),
    path("new-transaction", views.new_transaction, name='new_transaction'),
    path("new-transaction-iban", views.new_transaction_iban, name='new_transaction_iban'),
    path("verify-code", views.verify_code, name='verify_code'),
    path("verify-login", views.verify_login, name='verify_login'),
    path("transaction-list", views.transactions_list, name='transactions_list'),
    path("transaction-list-filter", views.transactions_list_filter, name='transactions_list_filter'),
    path("deposit", views.deposit, name='deposit'),
    path('detalii-user/<int:user_id>', views.user_details, name='user_details'),
    path('edit-user-profile/<int:user_id>', views.edit_user_profile, name='edit_user_profile'),
    path('delete-user/<int:user_id>', views.delete_user, name='delete_user'),
    path('create-user', views.create_user, name='create_user'),
    path('change-contract/<int:user_id>', views.change_contract, name='change_contract'),
    path('admin-panel', views.admin_panel, name='admin_panel'),

]

FederalBank/bank/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, blank=True)
    iban = models.CharField(max_length=200, null=True)
    phone = PhoneNumberField()
    company_name = models.CharField(max_length=200, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    contract_start_date = models.DateField(null=True, blank=True)
    contract_end_date = models.DateField(null=True, blank=True)
    amount = models.PositiveIntegerField(default=0,validators=[
            MaxValueValidator(999999999),
            MinValueValidator(0),
        ])

class Transaction(models.Model):
    from_user = models.ForeignKey(User, null=True,  on_delete=models.CASCADE,  related_name='from_user')
    to_user = models.ForeignKey(User, null=True,  on_delete=models.CASCADE, related_name='to_user')
    date = models.DateTimeField(default=datetime.now, blank=True)
    details = models.CharField(max_length=250)
    code = models.IntegerField(validators=[
            MaxValueValidator(999999),
            MinValueValidator(10000),
        ])
    amount = models.PositiveIntegerField(null=True, validators=[
        MaxValueValidator(999999999),
        MinValueValidator(0),
    ])


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

FederalBank/bank/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User
from .models import Profile,Transaction
from phonenumber_field.formfields import PhoneNumberField
from datetime import date


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'username', "password1", "password2")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('address', 'phone', 'company_name','birth_date')
        phone = PhoneNumberField()

    def clean_date_of_birth(self):
        error = False
        dob = self.cleaned_data['birth_date']
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            error = True
        return error


class ResetPasswordFrom(forms.Form):
    password1 = forms.CharField()
    password2 = forms.CharField()


class ContractForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('contract_start_date', 'contract_end_date')

class TransactionForm(forms.Form):
    phone = PhoneNumberField()
    amount = forms.IntegerField()
    details = forms.CharField(required=False)

class TransactionIbanForm(forms.Form):
    iban = forms.CharField()
    amount = forms.IntegerField()
    details = forms.CharField(required=False)

class CodeForm(forms.Form):
    code = forms.CharField()

class DepositForm(forms.Form):
    number = forms.CharField()
    date = forms.CharField()
    cv = forms.CharField()
    name = forms.CharField()
    amount = forms.IntegerField()

class DateFilterForm(forms.Form):
    from_date = forms.DateTimeField()
    to_date = forms.DateTimeField()


class EditProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User

        fields = (
            'email',
            'first_name',
            'last_name',
        )



GROUP_NAMES = (
    ('Administrator', 'Administrator'),
    ('SuportClient', 'SuportClient'),
    ('Client', 'Client')
)

class SimpleForm(forms.Form):
    choice = forms.ChoiceField(required=True, choices=GROUP_NAMES)

FederalBank/bank/views.py
import os
import string
from datetime import datetime
import random

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render
from django.contrib.auth.models import User
from twilio.rest import Client

from .models import Profile, Transaction
from django.contrib import messages
from django.contrib.auth import get_user_model
from .forms import SignUpForm, EditProfileForm, PasswordChangeForm, ProfileForm, SimpleForm, ContractForm, TransactionForm,\
    CodeForm, DateFilterForm,DepositForm, ResetPasswordFrom,TransactionIbanForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import Group
from datetime import datetime
UserModel = get_user_model()
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage, InvalidPage




def index(request):
    return render(request, 'bank/index.html')


def register(request):
    form = SignUpForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None)
    if form.is_valid() and profile_form.is_valid():

        user = form.save(commit=False)
        profile = profile_form.save(commit=False)
        phone = profile_form.cleaned_data['phone']
        user.is_active = True
        profile.user = user
        if   profile_form.cleaned_data['birth_date'] == None:
            age_error = True
        else:
            age_error = profile_form.clean_date_of_birth()

        number_error = False
        all_users = User.objects.all()
        # for usr in all_users:
        #    if usr.profile.phone == phone:
        #        number_error = True

        if(age_error or number_error):
            context = None
            if age_error == True and number_error ==False:
                context = {
                    "form": form,
                    "profile_form": profile_form,
                    "error_message": "Trebuie sa ai minim 18 ani!"
                }
            elif age_error == False and number_error ==True:
                context = {
                    "form": form,
                    "profile_form": profile_form,
                    "error_message": "Exista deja un cont asociat numarului de telefon!"
                }
            elif age_error == True and number_error ==True:
                context = {
                    "form": form,
                    "profile_form": profile_form,
                    "error_message": "Trebuie sa ai minim 18 ani si exista deja un cont asociat numarului de telefon!"
                }

            return render(request, 'bank/register.html', context)
        else:

            user.save()
            profile.save()

            group = Group.objects.get(name='Client')
            user.groups.add(group)

            return redirect(acc_created)

    context = {
        "form": form,
        "profile_form":profile_form,
    }
    return render(request, 'bank/register.html', context)


def acc_created(request):
    return render(request, 'bank/acc_created.html')



def login_usr(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        login_code = random.randint(100000, 999999)
        print(login_code)

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                if user.groups.all()[0].name == 'Client':

                    # VERIFICARE TELEFON
                    user_phone_number = user.profile.phone
                    account_sid = 'ACace5127e57ef0641719a6d6e7af6519a'
                    auth_token = '7b2564002f0b7eab27b452691b7b4d23'
                    client = Client(account_sid, auth_token)

                    message = client.messages \
                        .create(
                        body=f"Salut {user.first_name}, te-ai conectat la contul tau de Federal Bank.Codul de confirmare este {login_code}",
                        from_='+17038103944',
                        to=str(user_phone_number)
                    )

                    print(message.sid)


                    request.session['login_details'] = {}
                    upd = {
                        'login_code': login_code,
                        'username' :username,
                        'password': password,
                    }
                    request.session['login_details'].update(upd)
                    return redirect(verify_login)
                else:
                    login(request, user)

                    return redirect(admin_panel)

            else:
                return render(request, 'bank/login.html')
        else:
            return render(request, 'bank/login.html', {'error_message': 'Invalid login'})
    return render(request, 'bank/login.html')


def admin_panel(request):

    return render(request, 'bank/admin_panel.html')

def verify_login(request):
    form = CodeForm(request.POST or None)

    if request.method == 'POST':
        form = CodeForm(request.POST or None)
        if form.is_valid():
            code = form.cleaned_data['code']

            if 'login_details' in request.session:
                transaction_details = request.session['login_details']

                if str(code) == str(transaction_details['login_code']):
                    user = authenticate(username=transaction_details['username'], password=transaction_details['password'])
                    login(request, user)

                    return redirect(client_menu)


        else:

            form = CodeForm(request.POST or None)
            context = {'form': form,
                       }

            return render(request, 'bank/verify_login.html', context)

    context = {'form': form,
               }

    return render(request, 'bank/verify_login.html', context)



def logout_usr(request):
    logout(request)

    return redirect(index)


def profile(request):



    context = {'user': request.user,

               }

    return render(request, 'bank/profile.html', context)


def edit_profile(request):
    user = request.user

    form = EditProfileForm(request.POST, instance=user)
    profile_form = ProfileForm(request.POST, instance=user)
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, instance=user)
        if form.is_valid() and profile_form.is_valid():
            form.save()

            usr = form.save(commit=False)

            prf = Profile.objects.filter(user=user)
            current_profile = prf.get()
            phone = profile_form.cleaned_data['phone']
            company_name = profile_form.cleaned_data['company_name']
            address = profile_form.cleaned_data['address']
            current_profile.user = usr
            current_profile.phone = phone
            current_profile.company_name = company_name
            current_profile.address = address

            usr.save()
            profile_form.save()
            current_profile.save()

            return redirect(profile)


    else:
        form = EditProfileForm(instance=user)
        profile_form = ProfileForm(request.POST, instance=user)
        context = {'form': form, 'profile_form':profile_form,  'user':user}

        return render(request, 'bank/edit_profile.html', context)

    context = {'form': form, 'profile_form': profile_form, 'user':user}

    return render(request, 'bank/edit_profile.html', context)




def change_password(request):
    form = PasswordChangeForm(data=request.POST, user=request.user)
    posted = None
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        posted = True

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Parola ta a fost schimbata cu succes!!')
            return redirect(password_changed)
        else:
            context = {'form': form,
                       'posted': posted,

                       }
            return render(request, 'bank/change_password.html', context)

    context = {'form': form,
               'posted': posted,

               }

    return render(request, 'bank/change_password.html', context)


def password_changed(request, ):
    return render(request, 'bank/password_changed.html')

def reset_password(request, user_id):

    user = User.objects.get(id=user_id)
    form = ResetPasswordFrom(request.POST or None)
    password_error = False

    if request.method == 'POST':
        form = ResetPasswordFrom(request.POST or None)


        if form.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']


            if password1 == password2:
                user.set_password(password1)
                user.save()

                return redirect(administrator_menu)
            else:
                password_error = True

                context = {'form': form,
                           'password_error': password_error
                           }
                return render(request, 'bank/reset_password.html', context)

        else:
            context = {'form': form,
                       'password_error': password_error

                       }
            return render(request, 'bank/reset_password.html', context)

    context = {'form': form,
               'password_error': password_error

               }

    return render(request, 'bank/reset_password.html', context)




def administrator_menu(request):
    users = User.objects.filter(groups__name__in=['Client'])|User.objects.filter(groups__name__in=['SuportClient'])
    paginator = Paginator(users, 10)
    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1

    try:
        users_page = paginator.page(page)

FederalBank/bank/templates/bank/admin_panel.html
{% extends 'bank/base_template.html' %}

{% block title %}Acasa{% endblock %}



{% block style %}
    {% load static %}
    <link href="{% static 'bank/css/admin_panel.css' %}" rel="stylesheet">
{% endblock %}


{% block body %}
<div class="container" style="padding-top: 350px; padding-bottom: 480px">
    <div class="row">
    <div class="col-md-3">
      <div class="card-counter primary">
        <i class="fa fa-code-fork"></i>
        <span class="count-numbers">12</span>
        <span class="count-name">Flowz</span>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card-counter danger">
        <i class="fa fa-ticket"></i>
        <span class="count-numbers">599</span>
        <span class="count-name">Instances</span>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card-counter success">
        <i class="fa fa-database"></i>
        <span class="count-numbers">6875</span>
        <span class="count-name">Data</span>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card-counter info">
        <i class="fa fa-users"></i>
        <span class="count-numbers">35</span>
        <span class="count-name">Users</span>
      </div>
    </div>
  </div>
</div>







{% endblock %}

FederalBank/bank/templates/bank/change_contract.html
{% extends 'bank/base_template.html' %}
{% block title %}Ingresitrare{% endblock %}


{% block style %}


{% endblock %}s

{% block body %}

{% if profile_form.errors  %}
    <div class="alert alert-danger" role="alert">{{profile_form.errors}}</div>
{% endif %}



<main class="my-form" style="padding-top: 100px; padding-bottom: 380px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">SCHIMBA SAU ADAUGA UN NOU CONTRACT</div>
                        <div class="card-body">
                            <form  method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                  <div class="form-group row">
                                    <label for="contract_start_date" class="col-md-4 col-form-label text-md-right">Data inceperii contractului:</label>
                                    <div class="col-md-6">
                                        <input type="date" id="contract_start_date"  name="contract_start_date" class="form-control">
                                    </div>
                                </div>

                                     <div class="form-group row">
                                    <label for="contract_end_date" class="col-md-4 col-form-label text-md-right">Data inceperii contractului:</label>
                                    <div class="col-md-6">
                                        <input type="date" id="contract_end_date"  name="contract_end_date" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            Salveaza modificarile
                                        </button>
                                    </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

FederalBank/bank/templates/bank/index.html
{% extends 'bank/base_template.html' %}

{% block title %}Acasa{% endblock %}



{% block style %}
    {% load static %}
    <link href="{% static 'bank/css/index.css' %}" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="mid" style="padding-bottom: 400px">
        <video autoplay muted loop>
                {% load static %}
                <source class="embed-responsive" src="{% static 'bank/video/1.mp4' %}" type="video/mp4">
        </video>

        <div class="hero text-center">
            <h2 class="text-light display-4 font-weight-bold">Web Aplication Banking</h2>
            <p class="text-light mx-auto">Sperăm ca noua interfață ușor de navigat și noile funcționalități  din aplicația
                    Federal Bank <br> te ajută să te bucuri mai ușor ca oricând de banking pe desktop.</p>
            <a class="text-dark" href="{% url 'register' %}">Sa incepem!</a>

        </div>

</div>


{% endblock %}

FederalBank/bank/templates/bank/new_transaction.html
{% extends 'bank/base_template.html' %}
{% block title %}Ingresitrare{% endblock %}


{% block style %}


{% endblock %}s

{% block body %}

{% if form.errors  %}
                     <div class="alert alert-danger" role="alert">{{form.errors}}</div>
{% endif %}

{% if phone_error  %}
                     <div class="alert alert-danger" role="alert">Nu exista nici un user cu acest numar de telefon!</div>
{% endif %}


{% if amount_error  %}
                     <div class="alert alert-danger" role="alert">Fonduri insuficiente!</div>
{% endif %}
{% if current_user_error  %}
                     <div class="alert alert-danger" role="alert">Numarul de telefon este al dumneavoastra.</div>
{% endif %}


<main class="my-form" style="padding-bottom: 300px; padding-top: 100px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
						<div class="card-header"><h1>Tranzactie noua</h1></div>
                        <div class="card-body">
                            <form  method="post" enctype="multipart/form-data">
                                {% csrf_token %}



								<div class="form-group row">
									<label for="id_phone" class="col-md-4 col-form-label text-md-right">Telefon:</label>
                                    <div class="col-md-6">
                                        <input type="tel" class="form-control" id="id_phone" required="" name="phone" >
                                    </div>
                                </div>

								<div class="form-group row">
									<label for="id_amount" class="col-md-4 col-form-label text-md-right">SUMA:</label>
                                    <div class="col-md-6">
                                        <input type="number" class="form-control" required="" id="id_amount" name="amount">
                                    </div>
                                </div>

                                <div class="form-group row">
									<label for="id_details" class="col-md-4 col-form-label text-md-right">Detali:</label>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" id="id_details" name="details">
                                    </div>
                                </div>

                                    <div class="col-md-6 offset-md-4">
                                        <button class="btn btn-success" type="submit">
                                            Finalizeaza tranzactia
                                        </button>
                                    </div>

                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>

</main>


{% endblock %}

FederalBank/bank/templates/bank/new_transaction_iban.html
{% extends 'bank/base_template.html' %}
{% block title %}Ingresitrare{% endblock %}


{% block style %}


{% endblock %}s

{% block body %}
{% if form.errors  %}
                     <div class="alert alert-danger" role="alert">{{form.errors}}</div>
{% endif %}

{% if phone_error  %}
                     <div class="alert alert-danger" role="alert">Codul IBAN este invalid!</div>
{% endif %}


{% if amount_error  %}
                     <div class="alert alert-danger" role="alert">Fonduri insuficiente!</div>
{% endif %}

{% if current_user_error  %}
                     <div class="alert alert-danger" role="alert">Codul IBAN corespunde contului curent!</div>
{% endif %}


<main class="my-form" style="padding-bottom: 300px; padding-top: 100px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
						<div class="card-header"><h1>Tranzactie noua</h1></div>
                        <div class="card-body">
                            <form  method="post" enctype="multipart/form-data">
                                {% csrf_token %}



								<div class="form-group row">
									<label for="id_iban" class="col-md-4 col-form-label text-md-right">IBAN:</label>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" id="id_iban" required="" name="iban" >
                                    </div>
                                </div>

								<div class="form-group row">
									<label for="id_amount" class="col-md-4 col-form-label text-md-right">SUMA:</label>
                                    <div class="col-md-6">
                                        <input type="number" class="form-control" required="" id="id_amount" name="amount">
                                    </div>
                                </div>

                                <div class="form-group row">
									<label for="id_details" class="col-md-4 col-form-label text-md-right">Detali:</label>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" id="id_details" name="details">
                                    </div>
                                </div>

                                    <div class="col-md-6 offset-md-4">
                                        <button class="btn btn-success" type="submit">
                                            Finalizeaza tranzactia
                                        </button>
                                    </div>

                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>

</main>



{% endblock %}

FederalBank/bank/templates/bank/password_changed.html
{% extends 'bank/base_template.html' %}

{% block title %}Acasa{% endblock %}



{% block style %}
{% load static %}
        <link href="{% static 'bank/css/password_changed.css' %}" rel="stylesheet">


{% endblock %}


{% block body %}



  <div class="container" style="padding-bottom: 400px">
      <div>
          <p>Parola a fost schimbata cu succes!</p>
          <a href="{% url 'profile' %}" class="btn btn-success" href="">Vezi profil</a>
      </div>
    </div>
{% endblock %}

FederalBank/bank/templates/bank/verify_code.html
{% extends 'bank/base_template.html' %}
{% block title %}Verificare user{% endblock %}


{% block style %}


{% endblock %}s

{% block body %}
{% if form.errors  %}
    <div class="alert alert-danger" role="alert">{{form.errors}}</div>
{% endif %}

{% if invalid_code  %}
    <div class="alert alert-danger" role="alert">Codul nu este valid!Mai aveti{% if tries %} {{tries}}{% endif %} incercari!</div>
{% endif %}

<main class="my-form" style="padding-bottom: 350px; padding-top: 100px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header"><h1>COD DE VERIFICARE</h1></div>
                        <div class="card-body">
                            <form  method="post">
                                {% csrf_token %}

                                 <div class="form-group row">
                                    <label for="id_code" class="col-md-4 col-form-label text-md-right">Codul primit prin SMS:</label>
                                    <div class="col-md-6">
                                        <input type="text"  id="id_code" class="form-control"  required="" name="code">
                                    </div>
                                </div>
                                <div class="col-md-6 offset-md-4">
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-success">Verifica</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>

</main>

{% endblock %}s

FederalBank/bank/templates/bank/verify_login.html
{% extends 'bank/base_template.html' %}
{% block title %}Verificare cod{% endblock %}


{% block style %}


{% endblock %}

{% block body %}

{% if form.errors  %}
    <div class="alert alert-danger" role="alert">{{form.errors}}</div>
{% endif %}

<main class="my-form" style="padding-bottom: 470px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header"><h1>COD DE VERIFICARE</h1></div>
                        <div class="card-body">
                            <form  method="post">
                                {% csrf_token %}
                                 <div class="form-group row">
                                    <label for="id_code" class="col-md-4 col-form-label text-md-right">Codul primit prin SMS:</label>
                                    <div class="col-md-6">
                                        <input type="text"  id="id_code" class="form-control" required="" name="code">
                                    </div>
                                </div>
                                 <div class="col-md-6 offset-md-4">
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-success">Verifica</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}